import React from 'react';
import Head from 'next/head';
import Nav from './Nav';
import Footer from './Footer';

function Layouts({ children }) {
    return (
        <>
            <Head>
                <title>Game Horder</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                {children}
            </main>
            <Footer />
        </>
    )
}

export default Layouts